import app_config from "@config/app_config";
import setup_type from "./setup_type";

const prefix: string = "LiveCourse";

const setup: setup_type = {
    prefix,
    permission: ["admin", "super_admin"],

    api_host: app_config.api_host,
    api_version: app_config.api_version,
    api_end_point: "live-courses",

    module_name: "live-course",
    store_prefix: "live_course",
    route_prefix: "LiveCourse",
    route_path: "live-course",

    select_fields: [
        "id",
        "title",
        "description",
        "live_course_type",
        "promo_video_url",
        "course_features",
        "course_specification",
        "course_duration",
        "thumbnail",
        "total_seats",
        "regular_price",
        "sale_price",
        "discount_percent",
        "installment_months",
        "is_popular",
        "sort_order",
        "status",
        "slug",
        "created_at",
        "deleted_at",
    ],

    sort_by_cols: [
        "id",
        "title",
        "description",
        "live_course_type",
        "promo_video_url",
        "course_features",
        "course_specification",
        "course_duration",
        "thumbnail",
        "total_seats",
        "regular_price",
        "sale_price",
        "discount_percent",
        "installment_months",
        "is_popular",
        "sort_order",
        "status",
        "created_at",
    ],
    table_header_data: [
        "id",
        "title",
        "description",
        "live_course_type",
        "promo_video_url",
        "course_features",
        "course_specification",
        "course_duration",
        "thumbnail",
        "total_seats",
        "regular_price",
        "sale_price",
        "discount_percent",
        "installment_months",
        "is_popular",
        "sort_order",
        "status",
        "created_at",
    ],
    table_row_data: [
        "id",
        "title",
        "description",
        "live_course_type",
        "promo_video_url",
        "course_features",
        "course_specification",
        "course_duration",
        "thumbnail",
        "total_seats",
        "regular_price",
        "sale_price",
        "discount_percent",
        "installment_months",
        "is_popular",
        "sort_order",
        "status",
        "created_at",
    ],
    quick_view_data: [
        "id",
        "title",
        "description",
        "live_course_type",
        "promo_video_url",
        "course_features",
        "course_specification",
        "course_duration",
        "thumbnail",
        "total_seats",
        "regular_price",
        "sale_price",
        "discount_percent",
        "installment_months",
        "is_popular",
        "sort_order",
        "status",
        "created_at",
    ],

    layout_title: prefix + " Management",
    page_title: `${prefix} Management`,

    all_page_title: "All " + prefix,
    details_page_title: "Details " + prefix,
    create_page_title: "Create " + prefix,
    edit_page_title: "Edit " + prefix,
};

export default setup;
