
import app_config from "@config/app_config";
import setup_type from "./setup_type";

const prefix: string = "CourseBatch";

const setup: setup_type = {
    prefix,
    permission: ["admin", "super_admin"],

    api_host: app_config.api_host,
    api_version: app_config.api_version,
    api_end_point: "course-batches",

    module_name: "course-batch",
    store_prefix: "course_batch",
    route_prefix: "CourseBatch",
    route_path: "course-batch",

    select_fields: [
        "id",
        "course_id",
            "batch_name",
            "admission_start_date",
            "admission_end_date",
            "batch_student_limit",
            "seat_booked",
            "booked_percent",
            "course_price",
            "course_discount",
            "after_discount_price",
            "first_class_date",
            "class_days",
            "class_start_time",
            "class_end_time",
            "show_percentage_on_cards",
        "status",
        "slug",
        "created_at",
        "deleted_at",
    ],

    sort_by_cols: [
        "id",
        "course_id",
            "batch_name",
            "admission_start_date",
            "admission_end_date",
            "batch_student_limit",
            "seat_booked",
            "booked_percent",
            "course_price",
            "course_discount",
            "after_discount_price",
            "first_class_date",
            "class_days",
            "class_start_time",
            "class_end_time",
            "show_percentage_on_cards",
        "status",
        "created_at",
    ],
    table_header_data: [
        "id",
        "course_id",
            "batch_name",
            "admission_start_date",
            "admission_end_date",
            "batch_student_limit",
            "seat_booked",
            "booked_percent",
            "course_price",
            "course_discount",
            "after_discount_price",
            "first_class_date",
            "class_days",
            "class_start_time",
            "class_end_time",
            "show_percentage_on_cards",
        "status",
        "created_at",
    ],
    table_row_data: [
        "id",
        "course_id",
            "batch_name",
            "admission_start_date",
            "admission_end_date",
            "batch_student_limit",
            "seat_booked",
            "booked_percent",
            "course_price",
            "course_discount",
            "after_discount_price",
            "first_class_date",
            "class_days",
            "class_start_time",
            "class_end_time",
            "show_percentage_on_cards",
        "status",
        "created_at",
    ],

    layout_title: prefix + " Management",
    page_title: `${prefix} Management`,

    all_page_title: "All " + prefix,
    details_page_title: "Details " + prefix,
    create_page_title: "Create " + prefix,
    edit_page_title: "Edit " + prefix,
};

export default setup;
