import app_config from "@config/app_config";
import setup_type from "./setup_type";

const prefix: string = "LiveCourseEnrollment";

const setup: setup_type = {
    prefix,
    permission: ["admin", "super_admin"],

    api_host: app_config.api_host,
    api_version: app_config.api_version,
    api_end_point: "live-course-enrollments",

    module_name: "live-course-enrollment",
    store_prefix: "live_course_enrollment",
    route_prefix: "LiveCourseEnrollment",
    route_path: "live-course-enrollment",

    select_fields: [
        "id",
        "student_id",
        "batch_id",
        "live_course_id",
        "student_info",
        "enrolled_at",
        "payment_status",
        "amount_paid",
        "transaction_id",
        "amount",
        "payment_details",
        "method",
        "status",
        "slug",
        "created_at",
        "deleted_at",
    ],

    sort_by_cols: [
        "id",
        // "student_id",
        "batch_id",
        "live_course_id",
        "student_info",
        "enrolled_at",
        "payment_status",
        "amount_paid",
        "transaction_id",
        "amount",
        "payment_details",
        "method",
        "status",
        "created_at",
    ],
    table_header_data: [
        "id",
        // "student_id",
        "batch",
        "live_course",
        "student_info",
        "enrolled_at",
        "payment_status",
        "amount_paid",
        "transaction_id",
        "amount",
        "payment_details",
        "method",
        "status",
        "created_at",
    ],
    table_row_data: [
        "id",
        // "student_id",
        "batch_id",
        "live_course_id",
        "student_info",
        "enrolled_at",
        "payment_status",
        "amount_paid",
        "transaction_id",
        "amount",
        "payment_details",
        "method",
        "status",
        "created_at",
    ],
    quick_view_data: [
        "id",
        // "student_id",
        "batch_id",
        "live_course_id",
        "student_info",
        "enrolled_at",
        "payment_status",
        "amount_paid",
        "transaction_id",
        "amount",
        "payment_details",
        "method",
        "status",
        "created_at",
    ],

    layout_title: prefix + " Management",
    page_title: `${prefix} Management`,

    all_page_title: "All " + prefix,
    details_page_title: "Details " + prefix,
    create_page_title: "Create " + prefix,
    edit_page_title: "Edit " + prefix,
};

export default setup;
